---
- name: Azure Infrastructure Deployment
  hosts: localhost

  vars:
    resource_group: KE02_groep02_RG
    location: West Europe
    virtual_network: main
    address_prefixes: "10.0.0.0/16"
    admin_username: azureuser

  tasks:
    # Create Virtual Network
    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        location: "{{ location }}"
        address_prefixes: "{{ address_prefixes }}"

    # Create subnets
    - name: Create subnets
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network: "{{ virtual_network }}"
        name: "{{ item.name }}"
        address_prefix: "{{ item.prefix }}"
      loop:
        - { name: "front-end", prefix: "10.0.0.0/24" }
        - { name: "back-end", prefix: "10.0.1.0/24" }
        - { name: "stepping-stone", prefix: "10.0.2.0/24" }

    # Create Network Security Groups (NSGs)
    - name: Create Network Security Groups (NSGs)
      command: >
        az network nsg create
        --resource-group "{{ resource_group }}"
        --name "{{ item.name }}"
        --location "{{ location }}"
      loop:
        - { name: "front-end" }
        - { name: "back-end" }
        - { name: "stepping-stone" }

    # Create Network Interface for Virtual Machine
    - name: Create Network Interface for Virtual Machine
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}-nic"
        location: "{{ location }}"
        subnet_name: "{{ item.subnet }}"
        virtual_network: "{{ virtual_network }}"
        security_group: "{{ item.nsg }}"
        ip_configurations:
          - name: ipconfig1
            private_ip_address: "{{ item.private_ip }}"
            private_ip_allocation_method: "Static"
            public_ip_address_name: "{{ item.name }}-public-ip"
            public_ip_allocation_method: "{{ 'Static' if item.public_ip else 'Dynamic' }}"
      loop:
        - { name: "vm-front-end", subnet: "front-end", nsg: "front-end", public_ip: true, private_ip: "10.0.0.4" }
        - { name: "vm-back-end", subnet: "back-end", nsg: "back-end", public_ip: false, private_ip: "10.0.1.4" }
        - { name: "vm-stepping-stone", subnet: "stepping-stone", nsg: "stepping-stone", public_ip: true, private_ip: "10.0.2.4" }

    # Create Virtual Machines
    - name: Create Virtual Machines
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        location: "{{ location }}"
        vm_size: Standard_B1ls
        admin_username: "{{ admin_username }}"
        admin_password: "YourSecurePassword123!"
        ssh_password_enabled: yes
        image:
          offer: ubuntu-24_04-lts
          publisher: Canonical
          sku: server
          version: latest
        os_disk_name: "{{ item.name }}-osdisk"
        os_disk_caching: ReadWrite
        managed_disk_type: Standard_LRS
        network_interface_names:
          - "{{ item.name }}-nic"
      loop:
        - { name: "vm-front-end" }
        - { name: "vm-back-end" }
        - { name: "vm-stepping-stone" }