---
- name: Install Prometheus and Grafana
  hosts: localhost
  become: true
  vars:
    prometheus_version: "2.52.0"
    grafana_repo_url: "https://packages.grafana.com/oss/deb"  # or rpm, depending on system
    prometheus_user: prometheus
    prometheus_group: prometheus

  tasks:

  - name: Ensure necessary packages are installed (Ubuntu/Debian)
    apt:
      name: [wget, curl, tar]
      state: present
    when: ansible_os_family == "Debian"

  - name: Ensure necessary packages are installed (RHEL/CentOS)
    yum:
      name: [wget, curl, tar]
      state: present
    when: ansible_os_family == "RedHat"

  - name: Create prometheus user
    user:
      name: "{{ prometheus_user }}"
      shell: /sbin/nologin

  - name: Download Prometheus
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      dest: "/tmp/prometheus.tar.gz"

  - name: Extract Prometheus
    unarchive:
      src: "/tmp/prometheus.tar.gz"
      dest: "/opt/"
      remote_src: yes

  - name: Move Prometheus binaries
    copy:
      remote_src: yes
      src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      mode: '0755'
    loop:
      - prometheus
      - promtool

  - name: Create Prometheus directories
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ prometheus_user }}"
      group: "{{ prometheus_group }}"
    loop:
      - /etc/prometheus
      - /var/lib/prometheus

  - name: Copy Prometheus config
    copy:
      content: |
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']
      dest: /etc/prometheus/prometheus.yml
      owner: prometheus
      group: prometheus
      mode: '0644'

  - name: Create systemd unit file for Prometheus
    copy:
      dest: /etc/systemd/system/prometheus.service
      content: |
        [Unit]
        Description=Prometheus
        Wants=network-online.target
        After=network-online.target

        [Service]
        User=prometheus
        Group=prometheus
        Type=simple
        ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus

        [Install]
        WantedBy=multi-user.target
      mode: '0644'

  - name: Reload systemd and start Prometheus
    systemd:
      daemon_reload: yes
      name: prometheus
      enabled: yes
      state: started

  - name: Add Grafana APT repository (Debian/Ubuntu)
    apt_repository:
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present
      filename: grafana
    when: ansible_os_family == "Debian"

  - name: Add Grafana YUM repository (RHEL/CentOS)
    yum_repository:
      name: grafana
      description: Grafana OSS
      baseurl: https://packages.grafana.com/oss/rpm
      gpgcheck: yes
      gpgkey: https://packages.grafana.com/gpg.key
    when: ansible_os_family == "RedHat"

  - name: Install Grafana
    package:
      name: grafana
      state: present

  - name: Enable and start Grafana
    systemd:
      name: grafana-server
      enabled: yes
      state: started
