---
- name: Install MariaDB on back-end
  hosts: vm-back-end
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Installing dependancies & MariaDB-server on back-end..
      apt:
        name: [wget, curl, tar, mariadb-server]
        state: latest
        update_cache: yes
        
        

- name: Install NGINX and dependancies on front-end on front-end
  hosts: vm-front-end
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Installing dependancies & NGINX on front-end..
      apt:
        name: [wget, curl, tar, nginx]
        state: latest
        update_cache: yes
        
        
        
- name: Install dependancies on stepping-stone
  hosts: vm-stepping-stone
  become: true
  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Installing dependancies on stepping-stone..
      apt:
        name: [wget, curl, tar]
        state: latest
        update_cache: yes