---
- name: Azure Infrastructure Deployment
  hosts: localhost

  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Create Virtual Network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ virtual_network }}"
        location: "{{ location }}"
        address_prefixes: "{{ address_prefixes }}"

    - name: Create subnets
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        virtual_network_name: "{{ virtual_network }}"  
        name: "{{ item.name }}"
        address_prefix: "{{ item.prefix }}"
      loop: "{{ subnets }}"

    - name: Create NSGs
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"  
        location: "{{ location }}"
      loop: "{{ subnets }}"
      
    - name: Add NSG to subnets
      azure_rm_subnet:
        name: "{{ item.name }}"
        resource_group: "{{ resource_group }}"
        virtual_network_name:  "{{ virtual_network }}"
        address_prefix: "{{ item.prefix }}"
        security_group: "{{ item.name }}"
      loop: "{{ subnets }}"

    - name: Create Virtual Machines
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ item.name }}"
        location: "{{ location }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image: "{{ vm_image }}"
        subnet: "{{ item.subnet }}" #item.subnet of item.name?
        os_disk_name: "{{ item.name }}-osdisk"
        os_disk_caching: "{{ os_disk_caching }}"
        managed_disk_type: "{{ managed_disk_type }}"
      loop: "{{ vm_configs }}"