---
- name: Install MariaDB on back-end
  hosts: vm-back-end
  become: true
  vars_files:
    - ../group_vars/back_end.yml

  tasks:
    - name: Install MariaDB Server and dependancies on back-end
      apt:
        name: [wget, curl, tar, mariadb-server]
        state: latest
        update_cache: yes

- name: Install NGINX and dependancies on front-end on front-end
  hosts: vm-front-end
  become: true
  vars_files:
    - ../group_vars/front_end.yml

  tasks:
    - name: Install NGINX
      apt:
        name: [wget, curl, tar, nginx]
        state: latest
        update_cache: yes
        
- name: Install dependancies on stepping-stone
  hosts: vm-front-end
  become: true
  vars_files:
    - ../group_vars/front_end.yml

  tasks:
    - name: Install NGINX
      apt:
        name: [wget, curl, tar, nginx]
        state: latest
        update_cache: yes